import { Checkbox, Input, Radio, Select } from 'antd';
import type { FormItemType } from './types/itemType';
import type { ElementType } from 'react';
export * from './types/itemType';
const COMPONENTS_MAP = new Map<FormItemType, ElementType>();
COMPONENTS_MAP.set('input', Input);
COMPONENTS_MAP.set('select', Select);
COMPONENTS_MAP.set('radio', Radio);
COMPONENTS_MAP.set('checkbox', Checkbox);
COMPONENTS_MAP.set('radio-group', Radio.Group);
COMPONENTS_MAP.set('checkbox-group', Checkbox.Group);
export { COMPONENTS_MAP };
